# Generated by Django 3.0.5 on 2020-11-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikafka', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
