# Generated by Django 3.0.5 on 2020-11-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikafka', '0005_colortrends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colortrends',
        ),
    ]
