# Generated by Django 3.0.5 on 2020-11-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikafka', '0007_colortrends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colortrends',
            name='uuid',
        ),
    ]
